version: '3'

services:
  database:
    platform: linux/amd64
    image: postgis/postgis:15-3.4
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgis
    ports:
      - "${MY_DOCKER_IP:-127.0.0.1}:5439:5432"
    command: postgres -N 500
    volumes:
      - ./.pgdata:/var/lib/postgresql/data

  data_ingestion:
    platform: linux/amd64  
    build:
      context: .
      dockerfile: data_ingestion.dockerfile
    depends_on:
      - database
    environment:
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgis
    volumes:
      - ./postgres:/pg_scripts
    command: /bin/ash -c "/pg_scripts/download_parquet.sh && /pg_scripts/load_to_prod.sh"